### ISSUE TITLE
docs: for autocomplete 

### ISSUE THREAD

**Issue by chapmanjacobd** [kirchner/elm-selectize#11]
I already figured out that putting a Cmd.msg on textfieldSelection is a good way to capture selection

But what is a good way to access the value of Attributes.value query in autocomplete?

**Comment by kirchner** [comment]
I'm not 100% sure I understand what you mean. Generally, if you want to get the value of a text input field in Elm you add a sth like `Html.Events.onChanged ChangedTextfield` with `type Msg = ChangedTextfield String`. Since this library wraps the input field along with the dropdown menu, there is no way to get the actually value of the input field in Elm.
