### ISSUE TITLE
Allow multiple selection

### ISSUE THREAD

**Issue by amitaibu** [kirchner/elm-selectize#2]
I assume one could change the model to be something like:

```diff
type alias Model =
-   { selection : Maybe String
+   { selection : Maybe (List String)
    , menu : Selectize.State String
    }
```

Would have been lovely to see such an example (so I wouldn't have to do all the hard work, and just copy from what you've done 😉 )

**Comment by amitaibu** [comment]
(Sorry the issue was submitted to soon, I've updated the issue's description)

**Comment by amitaibu** [comment]
Actually, looking at [SharedConfig](https://github.com/kirchner/elm-selectize/blob/d7a0e1e8b2403f15b1caa19185791ca45951deb4/src/Selectize.elm#L236-L243) I'm not sure if that's currently possible. If I'm reading it correctly, maybe this should have changed to something like:

```diff
+ {-| Define the number of elements that can be selected. -}
+ type Cardinality = Limited Int | Unlimited

{-| The part of the configuration which is shared by `update` and `view`. -}
type SharedConfig a model
    = SharedConfig
        { toLabel : a -> String
        , state : model -> State a
        , entries : model -> List (Entry a)
-       , selection : model -> Maybe a
+       , selection : model -> List a
+       , cardinality : Cardinality
        , id : String
        }
```

**Comment by kirchner** [comment]
Are you thinking about a multiselect dropdown like for example the "tagging"-example from http://selectize.github.io/selectize.js/?  That would need a different view and update function. Maybe the application model could be

```elm
type alias Model =
    { selection : List a
    , menu : MultiSelectize.State a
    }
```

Then the shared config would be like you wrote and the update configuration perhaps

```elm
type alias UpdateConfig a msg :
    { appendSelection : a -> msg
    , removeSelection : Int -> msg
    }
```

The view configuration should then also include a function `renderSelectedEntry : a -> HtmlDetails Never`, so the user can style them.  Maybe this actually can return `HtmlDetails msg`, so one can add delete buttons at every entry?

The main difficulty is probably writing the view, so that the inputarea automatically increases vertically if there are a lot of selections.  And that the actual textfield "jumps" to the next line if the text gets too long. I guess, one could do that with this dom decoding trick as well though!

Im interested what you think how this multiselect should exactly look like and behave. :)

**Comment by amitaibu** [comment]
Good question, because there could be many different ways. But I think sticking to the example in Selectize are a good call. So the below example is a nice one:

![selectize_js](https://user-images.githubusercontent.com/125707/28997736-7fd555fa-7a24-11e7-9264-5e337c491e28.jpg)

> Maybe this actually can return HtmlDetails msg, so one can add delete buttons at every entry?

That sounds very similar to my use case, where there's an `x` on each "button" allowing it to be removed.

> I guess, one could do that with this dom decoding trick as well though!

@rgrempel has done some pretty fancy stuff around dom decoding in this [package](https://github.com/Gizra/elm-keyboard-event). Maybe it will be handy here as-well.

**Comment by kirchner** [comment]
Thanks for the link to the package!  I think your multi-select use-case (and the other ones on selectize.js) are all very useful.  But since there are so many different ways how a multiselect could be designed, it is best to make a separate package for each of them.  So please understand that im closing this issue here.
