### ISSUE TITLE
Multiselectize: Unselected item isn't immediately added back into dropdown

### ISSUE THREAD

**Issue by dunnl** [kirchner/elm-selectize#8]
(I am aware that MultiSelectize is not publicly released yet)

This issue shows up in both my own project and the [demo](https://kirchner.github.io/elm-selectize/). On the demo page, notice that if I select "Kermit the Frog" and then immediately unselect it, that item is not immediately available again in the dropdown. Instead, I have to close the dropdown first and then re-open it. Alternatively, if I select "Miss Piggy," "Kermit the Frog" is available in the dropdown without reopening it.

The cause is that the handler for the `UnselectAt` message does not touch the `state` in `Internal.MultiSelectize`, seen [here](https://github.com/kirchner/elm-selectize/blob/2d687439054b713abe62be53f6ed863ac37534c4/src/Internal/MultiSelectize.elm#L492). 
```
        UnselectAt position ->
            ( state
            , focus state.id
            , Just (unselect position)
            )
```

Not updating the state here means that the change will not be picked up in the internal state until after the user unselects the item in their own model. Then the internal update will notice the change in another `MultiSelectize.Msg` like `OpenMenu` or `Select.`

I can submit a PR later if this fix is desired.

**Comment by kirchner** [comment]
Thank you for pointing this bug out! I think you are right. This "cache" of entries along with their height in the state of the multiselect (`zipList`) seems to be the problem. I am not sure if there is a quick fix, since we do not know the height of the unselected entry. So, we cannot simply re-add it to this ziplist. We could perhaps remember its height when selecting it, but I think having this cache was not a good idea in the first place.

If i remember correctly I introduced it, to improve performance, but I think the really costly thing in this dropdown menu is rendering the actual dom elements. Decoding the necessary dom measurements (which is needed to adjust the scollposition, when navigating the menu using the keyboard) is actually not that expensive and can be done on every keypress. If one does this, there is no need for the ziplist anymore, and all these annoying caching bugs should be gone. If you have a lot of entries, improving performance is probably best done, by only rendering the visible entries like it is done in [FabienHenon/elm-infinite-list-view](http://package.elm-lang.org/packages/FabienHenon/elm-infinite-list-view/latest).

So I think, the real fix would be removing the zipList, which would probably mean a large rewrite of the module. And since I do not plan to release the multiselectize part, there is no need for a PR.

Nevertheless, thank you for offering your time and for reaching out first! :)
